# Generated by Django 3.2.23 on 2023-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
    ]
