# Generated by Django 5.0 on 2023-12-26 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointments",
            "0003_rename_healthcare_provider_appointment_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
